### ISSUE TITLE
Core doesn't compile in polyML 5.6

### ISSUE THREAD

**Issue by rossduncan** [zxcalc/quantomatic#150]
Mac OS 10.9.5, fresh build of polyML 5.6 release, fresh clone of quanto.  When making quanto core the build fails with the following error.

ML-Systems/polyml.ML:98: error: Value or constructor (profiling) has not been declared in structure PolyML
Found near PolyML.profiling
Exception- Fail "Static Errors" raised
Exception- Fail "Static Errors" raised
Exception trace for exception - Fail raised in ./basis/FinalPolyML.sml line 491
